[build]
  command = "yarn build"
  publish = "public/"
  functions = "lambda"

[context.production]
  command = "yarn build"

[context.deploy-preview]
  command = "yarn build"

[context.branch-deploy]
  command = "yarn build"
