backend:
  name: test-repo
  # branch: master
  squash_merges: true

media_folder: static/assets
public_folder: assets

collections:
  - label: "Menus"
    label_singular: "Menu"
    name: menus
    folder: menus
    create: true
    fields:
      - label: "Title"
        name: title
        widget: string
      - label: "Links"
        label_singular: "Link"
        name: links
        widget: list
        types:
          - name: link
            label: "Link"
            fields:
              - label: "Text"
                name: text
              - label: "URL"
                name: url
          - name: markdown
            label: "Markdown"
            fields:
              - label: "Title"
                name: title
              - label: "text"
                name: text
                widget: markdown
          - name: nested
            label: "Nested"
            fields:
              - label: "Title"
                name: title
              - label: "Links"
                name: links
                widget: list
                fields:
                  - label: "Text"
                    name: text
                  - label: "URL"
                    name: url

  - label: "General"
    name: general
    folder: general
    fields:
      - label: "Hero"
        name: hero
      - label: "Location"
        name: location
      - label: "Availability"
        name: availability
        widget: date

  - label: "Works"
    label_singular: "Work"
    name: works
    folder: works
    create: true
    fields:
      - label: "Meta"
        name: meta
        widget: object
        fields:
          - label: "Title"
            name: title
          - label: "Description"
            name: description
          - label: "Tags"
            name: tags
            widget: select
            options: [
              "Branding",
              "Design",
              "Development",
              "Product",
              "Website",
            ]
          - label: "Date"
            name: date
            widget: date
          - label: "Permalink"
            name: permalink
      - label: "Body"
        name: body
        widget: object
        fields:
          - label: "Title"
            name: title
          - label: "Description"
            name: description
          - label: "Case study"
            name: caseStudy
            widget: markdown

  - label: "Blog"
    label_singular: "Blog post"
    name: blog
    folder: blog
    create: true
    fields:
      - label: "Title"
        name: title
      - label: "Description"
        name: description
      - label: "Permalink"
        name: permalink
      - label: "Date"
        name: date
        widget: date
      - label: "ogImage"
        name: ogImage
        widget: image
      - label: "Body"
        name: body
        widget: markdown
