backend:
  name: test-repo
  # branch: master
  squash_merges: true

media_folder: static/assets
public_folder: assets

development_overrides:
  backend:
    name: file-system
    api_root: "http://localhost:8000/api"

collections:
  - label: "Menus"
    label_singular: "Menu"
    name: menus
    folder: src/content/cms/menus
    create: true
    extension: mdx
    format: frontmatter
    fields:
      - label: "Title"
        name: title
        widget: string
      - label: "Links"
        label_singular: "Link"
        name: links
        widget: list
        types:
          - name: link
            label: "Link"
            fields:
              - label: "Text"
                name: text
              - label: "URL"
                name: url
          - name: markdown
            label: "Markdown"
            fields:
              - label: "Title"
                name: title
              - label: "text"
                name: text
                widget: markdown
          - name: nested
            label: "Nested"
            fields:
              - label: "Title"
                name: title
              - label: "Links"
                name: links
                widget: list
                fields:
                  - label: "Text"
                    name: text
                  - label: "URL"
                    name: url

  - label: "Pages"
    label_singular: "Page"
    name: pages
    folder: src/content/cms/pages
    create: true
    extension: mdx
    format: frontmatter
    fields: 
      - label: "Title"
        name: title
      - label: "Date"
        name: date
        widget: date
      - label: "Meta"
        name: meta
        widget: object
        fields:
          - label: "Title"
            name: title
          - label: "Description"
            name: description
          - label: "Permalink"
            name: permalink
          - label: "ogImage"
            name: ogImage
            widget: image
      - label: "Blocks"
        label_singular: "Block"
        name: blocks
        widget: list
        types:
          - label: "Hero"
            name: hero
            fields: 
              - label: "Title"
                name: title
          - label: "Body"
            name: body
            fields: 
              - label: "Body"
                name: body
                widget: markdown
          - label: "Location"
            name: location
            fields:
              - label: "Title"
                name: title
              - label: "Text"
                name: text
          - label: "Availability"
            name: availability
            fields:
              - label: "Title"
                name: title
              - label: "Date"
                name: date
                widget: date
          - label: "Form"
            name: form
            fields:
              - label: "Inputs"
                name: inputs
                widget: list
                types:
                  - label: "Text"
                    name: text
                    fields:
                      - label: "Name"
                        name: name
                        default: "name"
                      - label: "Label"
                        name: label
                      - label: "Required"
                        name: required
                        widget: boolean
                        default: true
                  - label: "Email"
                    name: email
                    fields:
                      - label: "Name"
                        name: name
                        default: "email"
                      - label: "Label"
                        name: label
                      - label: "Required"
                        name: required
                        widget: boolean
                      - label: "Error"
                        name: error
                  - label: "Textarea"
                    name: textarea
                    fields:
                      - label: "Name"
                        name: name
                        default: "name"
                      - label: "Label"
                        name: label
                      - label: "Description"
                        name: description
                      - label: "Required"
                        name: required
                        widget: boolean
                        default: true
                      - label: "Rows"
                        name: rows
                        widget: number
                        valueType: int
                  - label: "Radio"
                    name: radio
                    fields:
                      - label: "Name"
                        name: name
                        default: "name"
                      - label: "Label"
                        name: label
                      - label: "Description"
                        name: description
                      - label: "Required"
                        name: required
                        widget: boolean
                        default: true
                      - label: "Options"
                        name: options
                        widget: list
                        fields:
                          - label: "Value"
                            name: value
                          - label: "Label"
                            name: label
                  - label: "Submit"
                    name: submit
                    fields:
                      - label: "Name"
                        name: name
                        default: "name"
                      - label: "Label"
                        name: label
              - label: "Success"
                name: success
                widget: markdown

  - label: "Works"
    label_singular: "Work"
    name: works
    folder: src/content/cms/works
    extension: mdx
    format: frontmatter
    create: true
    fields:
      - label: "Title"
        name: title
      - label: "Description"
        name: description
      - label: "Date"
        name: date
        widget: date
      - label: "Meta"
        name: meta
        widget: object
        fields:
          - label: "Title"
            name: title
          - label: "Description"
            name: description
          - label: "Tags"
            name: tags
            widget: select
            multiple: true
            options: [
              "Branding",
              "Design",
              "Development",
              "Product",
              "Website",
            ]
          - label: "Permalink"
            name: permalink
      - label: "Body"
        name: body
        widget: markdown

  - label: "Blog"
    label_singular: "Blog post"
    name: blog
    folder: src/content/cms/blog
    create: true
    extension: mdx
    format: frontmatter
    fields:
      - label: "Title"
        name: title
      - label: "Description"
        name: description
      - label: "Permalink"
        name: permalink
      - label: "Date"
        name: date
        widget: date
      - label: "ogImage"
        name: ogImage
        widget: image
      - label: "Related"
        name: related
        widget: relation
        collection: blog
        searchFields: ["title", "permalink"]
        valueField: "permalink"
        displayFields: ["title"]
        multiple: true
      - label: "Body"
        name: body
        widget: markdown

  - label: "Legal"
    name: legal
    folder: src/content/cms/legal
    create: true
    extension: mdx
    format: frontmatter
    fields:
      - label: "Title"
        name: title
      - label: "Description"
        name: description
      - label: "Permalink"
        name: permalink
      - label: "Body"
        name: body
        widget: markdown
